print("I will now count my chickness:")
print("hens", 25+30/6)
print("Rooster" 100-25*3%4)
print("now i willl count the eggs")
print(3+2+1-54%2-1/4_+6)
print("is it true that 3+2<5-7?")
print(3+2<5-7)
print(("what is 3+?", 3+2)
print("what is 5-7?" 5-7)
print("oh, that's why it is false.")
print("how about some more")
print("is it greater?",5>-2)
print("is it greater or eaual?"5>= -2)
print("is it less or equal?", 5 <= -2)
