input_name = input("enter the name")
input_last = input("enter your last name")
input_age = input("age")
print(input_name,input_last, input_age)
print(type(input_age))
first_name=str(input("entr the age"))
